### ISSUE TITLE
source code release time

### ISSUE THREAD

**Issue by rmwor1d** [yerfor/Soft-DRGN#1]
Hi there, congratulation to you that this article has been accepted for publication, and I will appreciate it if you can tell me what's your schedule for source code release, congratulations again!

Best regards.

**Comment by yerfor** [comment]
Thanks for your attention! We are currently working on polishing the code, and the source code will be released before the paper is formally published.

**Comment by rmwor1d** [comment]
Get it, thanks for your reply!
